# Microservice: Health Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
  namespace: news-voyager
  labels:
    app: health
spec:
  selector:
    matchLabels:
      app: health
  replicas: 1
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - name: health
          image: deepanshurawat6/microservices-health:1.0.0-4
          resources:
            requests:
              cpu: 200m
              memory: 0.3Gi
            limits:
              cpu: 400m
              memory: 0.6Gi
          ports:
            - containerPort: 3012
          env:
            - name: BACKEND_URL
              value: "http://backend-service:3001"
          readinessProbe:
            httpGet:
              path: /health
              port: 3012
            initialDelaySeconds: 10
            periodSeconds: 5
