apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: news-voyager
data:
  MONGO_HOST: "mongodb.news-voyager.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DB: "newsVoyager"

--- 

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: news-voyager
type: Opaque
data:
  MONGO_USER: YWRtaW4=  # base64 encoded username if needed
  MONGO_PASSWORD: cGFzc3dvcmQ= # base64 encoded password if needed

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-pv
  namespace: news-voyager
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongodb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  replicas: 1
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: "/data/db"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi

--- 

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017