# Backend Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
  namespace: news-voyager
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: { duration: 30 }
        - setWeight: 60
        - pause: { duration: 30 }
        - setWeight: 80
        - pause: { duration: 30 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend-rollout
  template:
    metadata:
      labels:
        app: backend-rollout
    spec:
      containers:
        - name: backend
          image: deepanshurawat6/backend:1.0.0
          resources:
            requests:
              cpu: 300m
              memory: 0.5Gi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: uri
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5