# Backend Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
  namespace: news-voyager
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 30}
        - setWeight: 60
        - pause: {duration: 30}
        - setWeight: 80
        - pause: {duration: 30}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend-rollout
  template:
    metadata:
      labels:
        app: backend-rollout
    spec:
      containers:
        - name: backend
          image: deepanshurawat6/backend:1.0.0-9
          resources:
            requests:
              cpu: 300m
              memory: 0.5Gi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_DB
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_PASSWORD
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(MONGO_DB)?authSource=admin"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
