apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: news-voyager

resources:
  # Backend resources
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-rollout.yaml
  - backend-rollout-service.yaml
  
  # Frontend resources
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-rollout.yaml
  - frontend-rollout-service.yaml
  
  # Business microservice
  - business-deployment.yaml
  - business-service.yaml
  - business-rollout.yaml
  - business-rollout-service.yaml
  
  # Entertainment microservice
  - entertainment-deployment.yaml
  - entertainment-service.yaml
  - entertainment-rollout.yaml
  - entertainment-rollout-service.yaml
  
  # General microservice
  - general-deployment.yaml
  - general-service.yaml
  - general-rollout.yaml
  - general-rollout-service.yaml
  
  # Health microservice
  - health-deployment.yaml
  - health-service.yaml
  - health-rollout.yaml
  - health-rollout-service.yaml
  
  # Science microservice
  - science-deployment.yaml
  - science-service.yaml
  - science-rollout.yaml
  - science-rollout-service.yaml
  
  # Sports microservice
  - sports-deployment.yaml
  - sports-service.yaml
  - sports-rollout.yaml
  - sports-rollout-service.yaml
  
  # Technology microservice
  - technology-deployment.yaml
  - technology-service.yaml
  - technology-rollout.yaml
  - technology-rollout-service.yaml
  
  # Shared resources
  - ingress.yaml
  - mongodb-config.yaml