# Microservice: Technology Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: technology-rollout
  namespace: news-voyager
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 15}
        - setWeight: 60
        - pause: {duration: 15}
        - setWeight: 80
        - pause: {duration: 15}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: technology-rollout
  template:
    metadata:
      labels:
        app: technology-rollout
    spec:
      containers:
        - name: technology
          image: deepanshurawat6/microservices-technology:1.0.0-13
          resources:
            requests:
              cpu: 200m
              memory: 0.3Gi
            limits:
              cpu: 400m
              memory: 0.6Gi
          ports:
            - containerPort: 3015
          env:
            - name: BACKEND_URL
              value: "http://backend-rollout-service:3001"
          readinessProbe:
            httpGet:
              path: /technology/health
              port: 3015
            initialDelaySeconds: 10
            periodSeconds: 5
