# Microservice: Business Rollout Service
apiVersion: v1
kind: Service
metadata:
  name: business-rollout-service
  namespace: news-voyager
spec:
  ports:
    - port: 3010
      targetPort: 3010
  selector:
    app: business-rollout
  type: ClusterIP