# Microservice: Business Service
apiVersion: v1
kind: Service
metadata:
  name: business-service
  namespace: news-voyager
spec:
  selector:
    app: business
  ports:
    - port: 3010
      targetPort: 3010
  type: ClusterIP