# Microservice: Sports Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-deployment
  namespace: news-voyager
  labels:
    app: sports
spec:
  selector:
    matchLabels:
      app: sports
  replicas: 1
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
        - name: sports
          image: deepanshurawat6/microservices-sports:1.0.0-9
          resources:
            requests:
              cpu: 200m
              memory: 0.3Gi
            limits:
              cpu: 400m
              memory: 0.6Gi
          ports:
            - containerPort: 3014
          env:
            - name: BACKEND_URL
              value: "http://backend-service:3001"
          readinessProbe:
            httpGet:
              path: /health
              port: 3014
            initialDelaySeconds: 10
            periodSeconds: 5
