apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: news-voyager
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5173
  type: LoadBalancer