# Microservice: Entertainment Rollout Service
apiVersion: v1
kind: Service
metadata:
  name: entertainment-rollout-service
  namespace: news-voyager
spec:
  ports:
    - port: 3011
      targetPort: 3011
  selector:
    app: entertainment-rollout
  type: ClusterIP